title: NSMBW Resources
description: Speedrunning Resources
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  parse_block_html: true


url: https://just-the-docs.github.io
baseurl: "/NSMBW-Speedrun-Guides"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  

just_the_docs:

