title: NSMBW Resources
description: GTGR
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  parse_block_html: true


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  

just_the_docs:
  collections:
    general:
      name: General
    categories:
      name: Categories
