title: NSMBW Resources
remote_theme: just-the-docs/just-the-docs@v0.10.1
color_scheme: dark

collections:
  general:
    permalink: "/:collection/:path/"
    output: true
  categories:
    permalink: "/:collection/:path/"

just_the_docs:
  collections:
    general:
      name: General
    categories:
      name: Categories
