title: NSMBW Resources
description: GTGR
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  parse_block_html: true






  
collections:
  general:
    permalink: "/:collection/:path/"
    output: true
  categories:
    permalink: "/:collection/:path/"

just_the_docs:
  collections:
    general:
      name: General
    categories:
      name: Categories
